@startuml
skinparam linetype polyline
' Inheritance
Component <|-- Actuator
Component <|-- Sensor
Component <|-- LCD
Action <|-- ActionNumericAssignment
Action <|-- ActionLcd
Remote <|-- Keyboard
' NamedElement <|-- Component
' NamedElement <|-- Remote
' NamedElement <|-- State
' NamedElement <|-- App

' Abstract Class Declaration
abstract class NamedElement{
  name : String
}
abstract class Action<T> {
   value : String
   component : Component
}
abstract class Component {
  pin : Integer
}
abstract class Remote {
}
class ActionLcd<T> {
}
' Class Declaration
class App {
}
class Transition {
    next : State
    signal : SIGNAL
}
' Enum Declaration
enum SIGNAL {
   HIGH
   LOW
}

' All attributes
App -- "*" Component : components
App -- "1" Remote : remote
App -- "*" LCD : lcds
App -- "*" State : states
State -- "*" Action : actions
State -- "*" Transition : transitions

' Hide methods
hide Component methods
hide Action methods
hide SIGNAL methods
hide Transition methods
hide NamedElement methods
' Hide members
hide LCD members
hide ActionLcd members
hide Sensor members
hide App members
hide Actuator members
hide State members
@enduml